import os

SECRET_KEY = 'SUPERSECRETSECRET'
AUTHY_API_KEY = os.environ['DEMO_AUTHY_API_KEY']
VERIFY_SERVICE_SID = os.environ['VERIFY_SERVICE_SID']
TWILIO_ACCT_SID = os.environ['DEMO_TWILIO_ACCOUNT_SID']
TWILIO_AUTH_TOKEN = os.environ['DEMO_TWILIO_AUTH_TOKEN']